config/routes.rb
Rails.application.routes.draw do
  get 'answers/edit'
  # get 'questions/index'
  # get 'questions/show'
  # get 'questions/new'
  # get 'questions/edit'
  
  root 'questions#index'
  resources :questions do#これでquestionsコントローラーに関するルーティングを自動で用意してくれる
    resources :answers
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question #answerから見てquestionは一つに定まるという意味
  
  validates :content, presence: true
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy 
    #Questionは沢山のAnswerを持っているという意味
    # また、あるQuestionが削除された場合には、紐づくAnswerも全て削除されるという意味
    validates :name, presence:true
    validates :title, presence:true
    validates :content, presence:true
    
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    if @answer.update(answer_params)
      redirect_to question_path(@question), notice: 'Success!'
    else
      redirect_to question_path(@question), alert: 'Invalid!'
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
  end
  
  def update
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    if @answer.update(answer_params)
      redirect_to question_path(@question), notice: 'Success!'
    else
      flash[:alert] = 'Invalid'
      render :edit
    end
  end
  
  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question), notice: 'Deleted'
  end
  
  private
    def answer_params
      params.require(:answer).permit(:content, :name, :question_id)
    end
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  
  def index
    @questions = Question.all
  end

  def show
    # @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path, notice: 'Success!'
    else
      flash[:alert] = "Sava error!"
      render :new
    end
  end

  def edit
    # @question = Question.find(params[:id])
  end
  
  def update
    # @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to root_path, notice: 'Success!'
    else
      flash[:alert] = 'Sava error!'
      render :edit
    end
  end
  
  def destroy
    # @question = Question.find(params[:id])
    @question.destroy
    redirect_to root_path, notice: 'Success'
  end

  
  private
  
    def set_question
      @question = Question.find(params[:id])
    end
  
    def question_params
      params.require(:question).permit(:name, :title, :content)
    end
  
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/edit.html.erb
<div>
    <h2>Update answer</h2>
    <%= form_with model:[@question, @answer], local: true do |f| %>
        <div class="form-group">
            
            <div class="form-group">
                <label>Name</label>
                <%= f.text_field :name, class:"form-control" %>
            </div>
            
            <div class="form-group">
                <label>Content</label>
                <%= f.text_area :content, class:"form-control" %>
            </div>
            
            <div class="text-center">
                <%= f.submit "Update", class: "btn btn-primary" %>
            </div>
            
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qanda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
        <p class="text-success"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="text-danger"><%= flash[:alert] %></p>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
         <%= form_with model: @question, local: true do |f| %>
            
            <dev class="form-group">
                <label>Name</label>
                <%= f.text_field :name, class: "form-control" %>
            </dev>
            
            <dev class="form-group">
                <label>Title</label>
                <%= f.text_field :title, class: "form-control" %>
            </dev>
            
            <dev class="form-group">
                <label>Content</label>
                <%= f.text_area :content, class: "form-control" %>
            </dev>
            
            <div class="text-center">
                <%= f.submit "Save" , class: "btn btn-primary" %>
            </div>
            
            
         <% end %>

app/views/questions/edit.html.erb
<div>
     <div class="col-md-4 offset-md-4">
         <h2 class="text-center">Edit question</h2>
         <%= render 'form' %>
     </div>
</div>

app/views/questions/index.html.erb
<h2>Questions</h2>
<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">
            <thead class="thead-light">
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Menu</th>
                </tr>
            </thead>
            <tbody>
                <% @questions.each do |question| %>
                  <tr>
                      <td><%= question.id %></td>
                      <td><%= link_to question.title, question_path(question) %></td>
                      <td>[ <%= link_to 'Edit', edit_question_path(question) %> ] 
                      [ <%= link_to 'Delete', question_path(question), method: :delete, data:{ confirm: 'Are you sure?' } %> ]</td>
                  </tr>
                <%end%>
            </tbody>
        </table>
        <div>
            <%= link_to 'New question', new_question_path %>
        </div>
    </div>
</div>

app/views/questions/new.html.erb
<div>
     <div class="col-md-4 offset-md-4">
         <h2 class="text-center">New question</h2>
         <%= render 'form' %>
     </div>
</div>

app/views/questions/show.html.erb
<div class="row">
    <div class="col-md-12">
        <h2><%= @question.title %></h2>
        <div>
            Content: <%= @question.content %>
        </div>
        <div>
            Name: <%= @question.name %>
        </div>
        
        
        <hr>
        
        
        <div>
            <h3>Answers</h3>
            <table class="table table-striped">
                <% if @question.answers.any? %>
                
                <thead class="thead-light">
                    <tr>
                        <td>Answar</td>
                        <td>Name</td>
                        <td>Menu</td>
                    </tr>
                </thead>
                <tbody>
                    <% @question.answers.each do |answer| %>
                    <tr>
                        <td>
                            <%= answer.content %>
                        </td>
                        <td>
                            <%= answer.name %>
                        </td>
                        <td>
                            [ <%= link_to 'Edit', edit_question_answer_path(@question, answer) %> ]
                            [ <%= link_to 'Delete', question_answer_path(@question, answer), method: :delete, data:{ confirm: 'Are you sure?'} %> ]
                        </td>
                    </tr>
                    <% end %>
                </tbody>
                
                <% else %>
                <p>No answer yet.</p>
                <% end %>
            </table>
        </div>
        
        
        <h3>Post new answer.</h3>
        
        <%= form_with model: [@question, @answer], local: true do |f| %>
            <%= f.hidden_field :question_id, { value: @question.id} %>
            
            <div class="form-group">
                <label>Name</label>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            
            <div class="form-group">
                <label>Content</label>
                <%= f.text_area :content, class: 'form-control' %>
            </div>
            
            <div class="text-center">
                <%= f.submit "Post", class: 'btn btn-primary' %>
            </div>
        
        <% end %>
        
        <div>
            <%= link_to '> Home', root_path %>
        </div>
        
    </div>
</div>